spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "root"
    password: 1234
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true